config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  resources :users
  resources :user_payments
  root 'projects#index'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  location    :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  goal_amount :decimal(8, 2)    default(0.0), not null
#

class Project < ApplicationRecord
  belongs_to :user
  has_many :user_payments

  validates :title, presence: true
  validates :location, presence: true
  validates :user, presence: true

  geocoded_by :location
  after_validation :geocode

  def progress_to_goal
    if money_raised >= goal_amount
      "100"
    else
      (money_raised / self.goal_amount * 100).to_i.to_s
    end
  end

  def goal_amount_formatted
    Money.new(self.goal_amount * 100 , "USD").format
  end

  def money_raised
    self.user_payments.sum(:amount)
  end

  def money_raised_formatted
    Money.new(money_raised * 100, "USD").format
  end

  def average_contribution
    self.user_payments.average(:amount) || 0
  end

  def average_contribution_formatted
    Money.new(average_contribution * 100, "USD").format
  end

  def backed_by_string
    "#{self.user_payments.count} people have backed with an average amount of #{average_contribution_formatted}"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @location = Project.try(:first).try(:location)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :location, :goal_amount, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, value: project.title || "", placeholder: "My Awesome Project" %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, autofocus: true, value: project.description || "", placeholder: "We're going to plant flowers in the community garden" %>
  </div>

  <div class="field">
    <%= f.label :location, value: "Address" %>
    <%= f.text_field :location, autocomplete: "off", value: project.location ||  "", placeholder: "My Neighborhood" %>
  </div>

  <div class="field">
    <%= f.label :goal_amount %>
    <%= f.text_field :goal_amount, value: (project.goal_amount == 0.0 ? "" : project.goal_amount ), placeholder: "$100.00" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      Projects
      <small><%= link_to 'New Project', new_project_path, class: "btn btn-success pull-right" %></small> 
    </h1> 
  </div>
</div>

<div class="row">
  <ul class="list-group">
    <% @projects.sort{ |a,b| a.distance_from(@location) <=> b.distance_from(@location) }.each do |project| %>
    <li class="list-group-item">
      <h3>
        <% klazz = project.money_raised > project.goal_amount ? "progress-bar-success" : "progress-bar-primary" %>
        <div class="col-md-3 pull-right">
          <div class="progress progress-striped ">
            <div class="progress-bar progress-bar-custom <%= klazz %>" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.progress_to_goal %>%;">
              <%= project.money_raised_formatted unless project.progress_to_goal.to_i < 20 %>
              <span class="sr-only">50% Complete</span>
            </div>
          </div>
        </div>

        <a href="<%= project_path(project) %>">
          <%= project.title %>
        </a>
      </h3>
      <h5><%= project.location %></h5>
      <h5><%= "#{project.distance_from(@location).round(2) || 0.0} miles away" %></h5>
    </li>
    <% end %>
  </ul>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<h1>
  <%= @project.title %>
  <small><%= social_share_button_tag @project.title %></small>     
</h1>
<h3><%= @project.location %></h3>
<p><%= @project.description %></p>
<p>Organized by <%= @project.user.email %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to new_user_payment_path(:project_id => @project.id), class: "btn btn-block btn-lrg btn-danger" do %>
      <h1>Support This Project!</h1>
    <% end %>
    <h4 class="text-center"><%= @project.backed_by_string %></h4>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="jumbotron">
      <h3 class="text-center">Money Raised</h3>
      <h1 class="text-center"><%= @project.money_raised_formatted %></h1>
    </div>
  </div>

  <div class="col-md-6">
    <div class="jumbotron">
      <h3 class="text-center">Goal</h3>
      <h1 class="text-center"><%= @project.goal_amount_formatted %></h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="progress">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= @project.progress_to_goal %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @project.progress_to_goal %>%;">
        <%= "#{@project.progress_to_goal}\% Complete" %> 
        <span class="sr-only"><%= @project.progress_to_goal %> Complete</span>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@project.latitude},#{@project.longitude}&markers=#{@project.latitude},#{@project.longitude}&zoom=16&size=640x300&key=#{ENV['GOOGLE_MAPS_API_KEY']}", class: 'img-fluid img-rounded', alt: "#{@project.title} on the map"%>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @project.user == current_user %>
      <a href= <%= edit_project_path @project %> class="btn btn-primary">Edit This Event</a>
    <% else %>
      <a href="mailto:<%=@project.user.email%>" class="btn btn-info">Contact the organizer</a>
    <% end %> 
  </div>
</div>