config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  resources :users
  resources :user_payments
  root 'projects#index'
end

app/models/user_payment.rb
# == Schema Information
#
# Table name: user_payments
#
#  id               :integer          not null, primary key
#  user_id          :integer          not null
#  project_id       :integer          not null
#  stripe_charge_id :string           not null
#  amount           :decimal(8, 2)    not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class UserPayment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :project, presence: true
  validates :user, presence: true
  validates :stripe_charge_id, presence: true
  validates :amount, presence: true
  validates :amount, numericality: true

end

app/controllers/user_payment_controller.rb
class UserPaymentController < ApplicationController
  before_action :set_user_payment, only: [:show]
  before_action :set_cause

  def new
    @user_payment = UserPayment.new
  end

  def show
  end

  def create
    begin
      @amount = cause_params[:amount]

      customer = Stripe::Customer.create(
        :email => current_user.email,
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'DC Grit Contribution',
        :currency    => 'usd'
      )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    @user_payment = UserPayment.new(amount: @amount, cause: @cause, stripe_charge_id: charge.id)

    respond_to do |format|
      if @user_payment.save
        format.html { redirect_to @user_payment, notice: 'You have successfully contributed!' }
        format.json { render :show, status: :created, location: @user_payment }
      else
        format.html { render :new }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    def set_user_payment
      @user_payment = UserPayment.find(params[:id])
    end

    def set_cause
      @cause = Cause.find(cause_params[:cause_id])
      unless @cause
        flash[:error] = "No Cause Selected"
        redirect_to causes_path 
      end
    end


    def cause_params
      params.permit(:stripeToken, :cause_id, :amount)
    end

end

app/controllers/user_payments_controller.rb
class UserPaymentsController < ApplicationController
  before_action :set_user_payment, only: [:show]
  before_action :set_project

  def new
    @user_payment = UserPayment.new
  end

  def show
  end


  def create
    begin
      @amount = user_payment_params[:amount]

      @amount = @amount.gsub('$', '').gsub(',', '')

      begin
        @amount = Float(@amount).round(2)
      rescue
        flash[:error] = 'Charge not completed. Please enter a valid amount in USD ($).'
        redirect_to new_charge_path
        return
      end

      @amount = (@amount * 100).to_i # Must be an integer!

      if @amount < 500
        flash[:error] = 'Charge not completed. Donation amount must be at least $5.'
        redirect_to new_charge_path
        return
      end

      charge = Stripe::Charge.create(
        :amount => @amount,
        :currency => 'usd',
        :source => user_payment_params[:stripeToken],
        :description => 'Custom donation'
      )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end

    @user_payment = UserPayment.new(project_id: user_payment_params[:project_id] , 
                                    amount: user_payment_params[:amount],
                                    stripe_charge_id: charge.id)

    @user_payment.user = current_user
    respond_to do |format|
      if @user_payment.save
        format.html { redirect_to @project, notice: 'Charge was successful!' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_user_payment
      @user_payment = UserPayment.find(params[:id])
    end

    def set_project
      @project = Project.find(user_payment_params[:project_id])
      unless @project
        flash[:error] = "No Project Selected"
        redirect_to projects_path 
      end
    end

    def user_payment_params
      params.permit(:stripeToken, :project_id, :amount)
    end

end

app/helpers/user_payment_helper.rb
module UserPaymentHelper
end

app/views/user_payments/new.html.erb
<div class="row">
<div class='col-md-12'>
  <h1>Pitch In!</h1>
</div>
<div class='col-md-6 col-md-offset-3'>
  <div class='jumbotron'>
    <h2 class='text-center'> <%= @project.title %> </h2>
    <h4 class='text-center'>How much can you help?</h4>
    <%= form_tag user_payments_path do %>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>


    <div class="form-group">
      <label class="sr-only" for="amount">Amount (in dollars)</label>
      <div class="input-group">
        <div class="input-group-addon">$</div>
        <input type="text" class="form-control" name="amount" id="amount" placeholder="Amount">
      </div>
    </div>

    <input type="hidden" name="project_id" value="<%= params[:project_id] %>">

    <article>
      <%= hidden_field_tag(:stripeToken) %>
    </article>
    <button class="btn btn-primary" id='donateButton'>Donate</button>
    <% end %>
  </div>
</div>
</div>

<script src="https://checkout.stripe.com/checkout.js"></script>

<script>
var handler = StripeCheckout.configure({
  key: '<%= Rails.configuration.stripe[:publishable_key] %>',
  locale: 'auto',
  name: 'DC Grit',
  email: '<%= current_user.email %>',
  'allow-remember-me': false,
  description: '<%= @project.title %> in <%= @project.location %>',
  token: function(token) {
    $('input#stripeToken').val(token.id);
    $('form').submit();
  }
});

$('#donateButton').on('click', function(e) {
  e.preventDefault();

  $('#error_explanation').html('');

  var amount = $('input#amount').val();
  amount = amount.replace(/\$/g, '').replace(/\,/g, '')

  amount = parseFloat(amount);

  if (isNaN(amount)) {
    $('#error_explanation').html('<p>Please enter a valid amount in USD ($).</p>');
  }
  else if (amount < 5.00) {
    $('#error_explanation').html('<p>Donation amount must be at least $5.</p>');
  }
  else {
    amount = amount * 100; // Needs to be an integer!
    handler.open({
      amount: Math.round(amount)
    })
  }
});

// Close Checkout on page navigation
$(window).on('popstate', function() {
  handler.close();
});

</script>