config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  resources :users
  resources :user_payments
  root 'projects#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DC Grit</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato' %>

</head>

<body>
  <div class="container">
    <nav class="navbar navbar-default card">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <%=image_tag "logo.png", class: ' header-img img-responsive' %>
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <% if current_user %>
            <ul class="nav navbar-nav">
              <li><a href="<%= projects_path %>">Projects</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a rel="nofollow" data-method="delete" href="/users/sign_out">Sign Out</a></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="card">
        <%= yield %>
    </div>
  </div>

</body>
</html>